/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2025-12-23 06:00:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class ex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<p>\n");
      out.write("		01. 인터넷은 컴퓨터가 서로 연결되어 (TCP/IP)라는 통신 프로토콜을 이용하여 정보를	\n");
      out.write("		주고받는 전 세계의 (컴퓨터 네트워크)입니다. 인터넷을 통해 광범위한 정보와 서비스를 제공 할 수 있는데 \n");
      out.write("		그중 한 서비스가 (web)입니다.\n");
      out.write("	</p>\n");
      out.write("	<p>\n");
      out.write("		02. 웹은 기본적으로 (클라이언트/서버) 방식으로 동작합니다. \n");
      out.write("		(  클라이언트    (웹 브라우저))가 특정 페이지를 (서버)에 요청하면 이를 처리한 후 \n");
      out.write("		그 결과를 (클라이언트)에게 보내어 응답하는 것입니다. : \n");
      out.write("	</p>\n");
      out.write("	<p>\n");
      out.write("		03. (정적 웹 페이지)는 컴퓨터에 저장된 텍스트 파일을 그대로 보는 것이고, \n");
      out.write("		(동적 웹 페이지)는 저장된 내용을 다른 변수로 가공 처리하여 보는 것입니다.\n");
      out.write("	</p>\n");
      out.write("	<p>\n");
      out.write("		04. 웹 프로그래밍 언어는 클라이언트 측 실행 언어와 서버 측 실행 언어로 구분되며, \n");
      out.write("		자바를 기반으로 하는 (JSP/서블릿)는 서버 측 웹 프로그래밍 언어 중 하나입니다.\n");
      out.write("	</p>\n");
      out.write("	<p>\n");
      out.write("		05. (서블릿) 기술의 확장인 JSP는 유지 관리가 용이하고 빠른 개발이 가능하며 \n");
      out.write("		코드 길이를 줄일 수 있습니다.\n");
      out.write("	</p>\n");
      out.write("	<p>\n");
      out.write("		06. JSP 페이지는 하나의 (서블릿) 프로그램으로 변환되어 실행됩니다.\n");
      out.write("	</p>\n");
      out.write("	<p>\n");
      out.write("		07. JSP는 생성부터 파괴까지 번역 -> (컴파일) -> (초기화) -> 실행 -> 소멸의 과정을 거칩니다.\n");
      out.write("	</p>\n");
      out.write("	<p>\n");
      out.write("		08. JSP 애플리케이션은 이클립스를 이용하여 프로젝트를 생성한 후 \n");
      out.write("		(webapp)에 JSP 페이지를 작성하여 프로젝트를 실행합니다.	\n");
      out.write("	</p>\n");
      out.write("	<p>\n");
      out.write("		09. JSP 개발 환경 도구는 다음과 같습니다.\n");
      out.write("	</p>\n");
      out.write("	<table border=\"1\">\n");
      out.write("		<tr>\n");
      out.write("			<th>요소</th>\n");
      out.write("			<th>프로그램명</th>\n");
      out.write("			<th>설명</th>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td>자바 개발 환경</td>\n");
      out.write("			<td>(JDK)</td>\n");
      out.write("			<td>JSP는 HTML 코드 내에 자바 코드를 작성하기 때문에 자바 개발 도구가 반드시 설치되어 있어야 한다.</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td>(웹 서버)</td>\n");
      out.write("			<td>톰캣</td>\n");
      out.write("			<td>\n");
      out.write("				웹 프로그래밍 언어로 작성된 웹 페이지가 실행되어 웹 브라우저에 나타나도록 하기 위해 웹 컨테이너를 설치해야 한다.<br>\n");
      out.write("				JSP 웹 컨테이너로 자주 사용되는 것 중에서 가장 유명한 것은 톰캣이다.<br>\n");
      out.write("				톰캣은 오픈 소스 프로젝트로서 무료로 누구나 사용할 수 있다.\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td>통합 개발 환경</td>\n");
      out.write("			<td>(eclipse)</td>\n");
      out.write("			<td>\n");
      out.write("				JSP 코드를 작성한 후 이를 컴파일하여 오류를 검사하고 실행 결과를 확인할 수 있는 통합 개발 환경(IDE)으로<br> \n");
      out.write("				개발자들에게 가장 인기 있는 이 프로그램을 선택하여 설치한다.\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("	</table>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
