/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2025-12-24 03:14:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


		String greeting = "도서 쇼핑몰에 오신걸 환영합니다.";
		String tagline = "Welcome to Web Market!";
	
  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1766545920000L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1766545887000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDateTime");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>Welcome</title>\n");
      out.write("	<!-- 부트스트랩 연결 -->\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- 북마켓 프로젝트 만들기 -->\n");
      out.write("	<!-- <h1>Welcome to Book Shopping Mall</h1>\n");
      out.write("	<h3>Welcome to Web Market!</h3> -->\n");
      out.write("	\n");
      out.write("	");
      out.write("\n");
      out.write("	\n");
      out.write("	<!-- 헤더 타이틀 영역 -->\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 헤더(메뉴) 영역 -->\n");
      out.write("		<header class=\"pb-3 mb-4 border-bottom\">\n");
      out.write("	    <a href=\"./welcome.jsp\" class=\"d-flex align-items-center text-dark text-decoration-none\">\n");
      out.write("	    	<!-- 홈 아이콘 -->\n");
      out.write("		    <svg width=\"32\" height=\"32\" fill=\"currentColor\" class=\"bi bi-house-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("		  		<path d=\"M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z\"/>\n");
      out.write("		  		<path d=\"m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z\"/>\n");
      out.write("				</svg>\n");
      out.write("				<!-- 홈 메뉴 -->\n");
      out.write("		    <span class=\"fs-4\">Home</span>\n");
      out.write("	    </a>\n");
      out.write("    </header>\n");
      out.write("    ");
      out.write("\n");
      out.write("	\n");
      out.write("	<div class=\"container py-4\">\n");
      out.write("		\n");
      out.write("   \n");
      out.write("    <!-- 중간 타이틀 영역 -->\n");
      out.write("    <div class=\"p-5 mb-4 bg-body-tertiary rounded-3\">\n");
      out.write("      <div class=\"container-fluid py-5\">\n");
      out.write("        <h1 class=\"display-5 fw-bold\">");
      out.print( greeting );
      out.write("</h1>\n");
      out.write("        <p class=\"col-md-8 fs-4\">BookMarket</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- 본문 영역 -->\n");
      out.write("    <div class=\"row align-items-md-stretch text-center\">\n");
      out.write("      <div class=\"col-md-12\">\n");
      out.write("        <div class=\"h-100 p-5\">\n");
      out.write("        	<h3>");
      out.print( tagline );
      out.write("</h3>\n");
      out.write("        	\n");
      out.write("        	<!-- 현재 접속 시간 출력하기 -->\n");
      out.write("        	");

        		LocalDateTime now = LocalDateTime.now();
        		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm:ss a");
        		
        		String CT = now.format(formatter);
        		out.println("현재 접속 시간 : " + CT);
        	
      out.write("\n");
      out.write("        	\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write(" 		</div>\n");
      out.write(" 		\n");
      out.write(" 		<!-- footer 타이틀 영역 -->\n");
      out.write(" 		");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 푸터(바닥글) 영역 -->\n");
      out.write("    <footer class=\"pt-3 mt-4 text-body-secondary border-top\">\n");
      out.write("			&copy; BookMarket\n");
      out.write("		</footer>");
      out.write("\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
